import './style.css'
import projects from './data/projects.json'

// Render project cards
const projectsEl = document.getElementById('projects')
if (projectsEl) {
  projectsEl.innerHTML = projects
    .map(
      (p) => `
    <a href="${p.url}" target="_blank" rel="noopener" class="project-card block">
      <h3 style="color: var(--color-text); font-size: 1.125rem; margin: 0 0 0.5rem;">${p.name}</h3>
      <p style="color: var(--color-text-muted); font-size: 0.875rem; line-height: 1.5; margin: 0 0 1rem;">${p.description}</p>
      <div class="flex flex-wrap gap-2">
        ${p.tags.map((t) => `<span class="tag">${t}</span>`).join('')}
      </div>
    </a>
  `
    )
    .join('')
}

// Load stats from pre-built JSON (generated by scripts/fetch-stats.js)
async function loadStats() {
  try {
    const res = await fetch('/stats.json')
    if (!res.ok) return
    const stats = await res.json()

    const map = {
      prs: stats.total_prs,
      merged: stats.merged_prs,
      repos: stats.public_repos,
      contributions: stats.repos_contributed_to,
    }

    for (const [key, value] of Object.entries(map)) {
      const el = document.querySelector(`[data-stat="${key}"]`)
      if (el && value != null) {
        el.textContent = value >= 100 ? `${value}+` : value
      }
    }
  } catch {
    // Stats will show hardcoded fallback values from HTML
  }
}

loadStats()
